### PR TITLE
simplify logic for container types and add explicit query support for racks and pods

### PR DESCRIPTION
**Pull request by Roguelazer**

### CODE REVIEW

**Comment by Roguelazer** [comment]
@sloppyfocus or @JeremyGrosser probably

**Comment by JeremyGrosser** [comment]
Maybe it'd be better to enumerate all of the types by doing GET / against the api and caching the result?

**Comment by Roguelazer** [comment]
I'm trying to avoid interacting with the HTTP API at all. Do you know if there's something in the Python API that offers the same enumeration?

**Comment by sloppyfocus** [comment]
clusto.typelist is a dict mapping name of type -> class

**Comment by sloppyfocus** [comment]
helpfully, it also includes generic types such as "clustometa" and "resourcemanager"

**Comment by JeremyGrosser** [comment]
yeah, clusto.TYPELIST or clusto.DRIVERLIST are probably what you want, depending on whether you want types or drivers... Technically you shouldn't access these vars directly as they're specific to the implementation of schema.py, so if we ever drop out the sqlalchemy backend and replace it with something else you'll have to adapt.

**Pull request merged**
